### ISSUE TITLE
所以这东西到底有多大（

### ISSUE THREAD

**Issue by badnng** [SunnyDesignor/PowerfulWindSlickedBackHairCS-LX_Improve#2]
我建议是全部打包发个release。。。。。
不然不让用多线程真的草（
![image](https://github.com/SunnyDesignor/PowerfulWindSlickedBackHairCS-LX_Improve/assets/115983722/0b030930-4161-4e9c-991c-5bd0e3c93269)

**Comment by Muska-Ami** [comment]
你自己的问题吧
我用Aria2多线程正常下载

**Comment by Muska-Ami** [comment]
![image](https://github.com/SunnyDesignor/PowerfulWindSlickedBackHairCS-LX_Improve/assets/79651409/a6c752e7-3aaa-4b7e-adf7-2718925d486c)

**Comment by badnng** [comment]
啊？这是code Source.zip下载吗？（不会是他那边上传多少下多少才导致idm用不了多线程吧）

**Comment by badnng** [comment]
> ![image](https://github.com/SunnyDesignor/PowerfulWindSlickedBackHairCS-LX_Improve/assets/79651409/a6c752e7-3aaa-4b7e-adf7-2718925d486c)
> 

啊？这是code Source.zip下载吗？（不会是他那边上传多少下多少才导致idm用不了多线程吧）

**Comment by Muska-Ami** [comment]
> > ![image](https://user-images.githubusercontent.com/79651409/250709980-a6c752e7-3aaa-4b7e-adf7-2718925d486c.png)
> 
> 啊？这是code Source.zip下载吗？（不会是他那边上传多少下多少才导致idm用不了多线程吧）

是直接下源码，应该是因为流式传输而且没有给出大小才会单线程吧......
IDM没怎么用过

**Comment by badnng** [comment]
> > > ![image](https://user-images.githubusercontent.com/79651409/250709980-a6c752e7-3aaa-4b7e-adf7-2718925d486c.png)
> > 
> > 啊？这是code Source.zip下载吗？（不会是他那边上传多少下多少才导致idm用不了多线程吧）
> 
> 是直接下源码，应该是因为流式传输而且没有给出大小才会单线程吧......
> IDM没怎么用过

但是发了release之后的文件可以多线程

**Comment by Rain-0x01-39** [comment]
[已经PR了](https://github.com/SunnyDesignor/PowerfulWindSlickedBackHairCS-LX_Improve/pull/1)

他合并更改后从Release里发出来就没问题了

但是他现在用不了电脑，没法合并更改😅

**Comment by Rain-0x01-39** [comment]
[暂时从这里下载？](https://github.com/SZ2528/PowerfulWindSlickedBackHairCS-LX_Improve/releases)

**Comment by SunnyDesignor** [comment]
已删除源代码中不必要的文件，已发布可执行文件。
