### ISSUE TITLE
音乐太快了

### ISSUE THREAD

**Issue by huang2191** [SunnyDesignor/PowerfulWindSlickedBackHairCS-LX_Improve#3]
是负数的话就没画面了

**Comment by SunnyDesignor** [comment]
近日的版本已改进相关设置，合理调整Offset.txt可以让音画同步，如果还是存在问题请考虑清理后台或使用性能更好的电脑

**Comment by huang2191** [comment]
![SharedScreenshot](https://github.com/SunnyDesignor/PowerfulWindSlickedBackHairCS-LX_Improve/assets/110579349/2c96b97c-d41a-47e1-9a3e-3b7c80ea1f58)
这
